Algoritmo "exercicio1"
//Pergunte um número ao usuário e informe se este
//número é par ou ímpar
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número Inteiro: ")
leia(num)

se (num%2 = 0) entao
   escreva("O número", num, " é par")
senao
     escreva("O número", num, " é impar")
fimse
Fimalgoritmo