Algoritmo "Questao11"
// Elaborar um programa que apresente o valor de uma
//potência de uma base qualquer (Variável b) elevada
//a um expoente qualquer (Variável e),
//ou seja, de b^e
Var
// Seção de Declarações das variáveis 
b, ex: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Escreva um número para a base")
leia (b)
escreval ("Escreva um número para o expoente")
leia (ex)

escreval (b, " elevado a ", ex, " é igual a: ", b ^ ex)
Fimalgoritmo